"use client";
import Head from "next/head";
import { useState } from "react";
import Calendar from "@/components/Calendar";
import { type DateTime } from "@types";
import { NextPage } from "next";
import Spinner from "@/components/Spinner";
import Menu from "@/components/Menu"

const Home: NextPage = () => {
  const [date, setDate] = useState<DateTime>({
    jusDate: null,
    dateTime: null,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!date.dateTime && <Calendar setDate={setDate} date={date} />}
        {date.dateTime && false ? (
          <Menu />
        ) : (
          <div className="flex h-screen items-center justify-center">
            <Spinner />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
